version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./db/postgresql:/home/postgres:rw
    environment:
      POSTGRES_DB: "oif"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
      PGDATA: "/home/postgres/data/pgdata"
    ports:
      - 5432:5432